CREATE TABLE Products (
  id                    int NOT NULL, 
  name                  varchar(255) NOT NULL, 
  description           varchar(255), 
  category_id           int NOT NULL, 
  cultivation_method_id int NOT NULL, 
  harvest_season_id     int NOT NULL, 
  is_deleted            tinyint DEFAULT 0 NOT NULL, 
  CONSTRAINT pk_products
    PRIMARY KEY (id));
CREATE TABLE ProductsCategories (
  id          int GENERATED BY DEFAULT AS IDENTITY,
  name        varchar(255) NOT NULL,
  description varchar(255),
  parent_id   int NOT NULL,
  CONSTRAINT pk_products_categories
    PRIMARY KEY (id));
CREATE TABLE ProductionSteps (
  id          int NOT NULL, 
  product_id  int NOT NULL, 
  company_id  int NOT NULL, 
  step_type   varchar(255) NOT NULL, 
  description varchar(255), 
  step_date   date, 
  step_order  int NOT NULL, 
  location_id int, 
  CONSTRAINT pk_production_steps
    PRIMARY KEY (id));
CREATE TABLE HarvestSeasons (
  id          int NOT NULL, 
  name        varchar(255) NOT NULL, 
  month_start smallint NOT NULL, 
  month_end   smallint NOT NULL, 
  hemisphere  varchar(255) NOT NULL, 
  description varchar(255), 
  CONSTRAINT pk_harvest_seasons
    PRIMARY KEY (id));
CREATE TABLE Companies (
  id          int NOT NULL, 
  owner_id    int NOT NULL, 
  name        varchar(255) NOT NULL, 
  fiscal_code varchar(255) NOT NULL, 
  location_id int NOT NULL, 
  description varchar(255), 
  website_url varchar(255), 
  is_deleted  tinyint DEFAULT 0 NOT NULL, 
  CONSTRAINT pk_companies
    PRIMARY KEY (id));
CREATE TABLE CompaniesCertifications (
  id                 int NOT NULL, 
  company_id         int NOT NULL, 
  certification_id   int NOT NULL, 
  certificate_number varchar(255) NOT NULL, 
  issue_date         date NOT NULL, 
  expiry_date        date NOT NULL, 
  CONSTRAINT pk_companies_certifications
    PRIMARY KEY (id));
CREATE TABLE ProductsCertifications (
  id                 int NOT NULL, 
  product_id         int NOT NULL, 
  certification_id   int NOT NULL, 
  certificate_number varchar(255), 
  issue_date         date NOT NULL, 
  expiry_date        date,
  CONSTRAINT pk_products_certifications
      PRIMARY KEY (id));
CREATE TABLE Certifications (
  id           int NOT NULL, 
  name         varchar(255) NOT NULL, 
  description  varchar(255), 
  issuing_body varchar(255) NOT NULL, 
  is_active    tinyint DEFAULT 1 NOT NULL, 
  CONSTRAINT pk_certifications
    PRIMARY KEY (id));
CREATE TABLE Requests (
  id              int NOT NULL, 
  requester_id    int NOT NULL, 
  target_table_id int NOT NULL, 
  target_id       int NOT NULL, 
  request_type    char(255) NOT NULL, 
  payload         varchar(255) NOT NULL, 
  status          varchar(255) DEFAULT 'pending' NOT NULL, 
  curator_id      int NOT NULL, 
  decision_notes  varchar(255), 
  created_at      timestamp DEFAULT current_timestamp() NOT NULL, 
  reviewed_at     timestamp,
  CONSTRAINT pk_requests
      PRIMARY KEY (id));
CREATE TABLE ChangeLogs (
  id           int NOT NULL, 
  table_id     int NOT NULL, 
  record_id    int NOT NULL, 
  changed_by   int NOT NULL, 
  changed_at   timestamp NOT NULL, 
  changed_type char(255) NOT NULL, 
  changes      varchar(255) NOT NULL, 
  CONSTRAINT pk_change_logs
    PRIMARY KEY (id));
CREATE TABLE UsersCompanies (
  id         int NOT NULL, 
  user_id    int NOT NULL, 
  company_id int NOT NULL,
  CONSTRAINT pk_users_companies
      PRIMARY KEY (id));
CREATE TABLE Users (
  id              int NOT NULL, 
  username        varchar(255) NOT NULL, 
  email           varchar(255) NOT NULL, 
  password_hashed varchar(500) NOT NULL, 
  first_name      varchar(255) NOT NULL, 
  last_name       varchar(255) NOT NULL, 
  phone           varchar(255), 
  role_id         int NOT NULL, 
  is_deleted      tinyint DEFAULT 0 NOT NULL, 
  CONSTRAINT pk_users
    PRIMARY KEY (id));
CREATE TABLE UserRoles (
  id        int NOT NULL, 
  name      varchar(255) NOT NULL, 
  is_active tinyint DEFAULT 1 NOT NULL, 
  CONSTRAINT pk_user_roles
    PRIMARY KEY (id));
CREATE TABLE CultivationMethods (
  id          int NOT NULL, 
  name        varchar(255) NOT NULL, 
  description varchar(255), 
  is_active   tinyint DEFAULT 1 NOT NULL, 
  CONSTRAINT pk_cultivation_methods
    PRIMARY KEY (id));
CREATE TABLE Locations (
  id            int NOT NULL, 
  name          varchar(255) NOT NULL, 
  address       varchar(255) NOT NULL, 
  street_number varchar(255) NOT NULL, 
  city          varchar(255) NOT NULL, 
  latitude      numeric(19, 0), 
  longitude     numeric(19, 0), 
  location_type varchar(255), 
  type          varchar(255), 
  CONSTRAINT pk_locations
    PRIMARY KEY (id));
CREATE TABLE Orders (
  id                   int NOT NULL, 
  buyer_id             int NOT NULL, 
  seller_id            int NOT NULL, 
  total_amount         numeric(19, 0) NOT NULL, 
  status               varchar(255) DEFAULT 'pending' NOT NULL, 
  ordered_at           timestamp NOT NULL, 
  delivery_date        date, 
  delivery_location_id int NOT NULL, 
  CONSTRAINT pk_orders
    PRIMARY KEY (id));
CREATE TABLE OrderItems (
  id                 int NOT NULL, 
  order_id           int NOT NULL, 
  product_listing_id int NOT NULL, 
  quantity           int NOT NULL, 
  unit_price         numeric(19, 0) NOT NULL, 
  total_price        numeric(19, 0) NOT NULL, 
  CONSTRAINT pk_order_items
    PRIMARY KEY (id));
CREATE TABLE Events (
  id            int NOT NULL, 
  organizer_id  int NOT NULL, 
  title         varchar(255) NOT NULL, 
  description   varchar(255), 
  event_type_id int NOT NULL, 
  start_date    date NOT NULL, 
  end_date      date NOT NULL, 
  location_id   int NOT NULL, 
  is_active     tinyint DEFAULT 1 NOT NULL, 
  CONSTRAINT pk_events
    PRIMARY KEY (id));
CREATE TABLE EventPartecipants (
  id            int NOT NULL, 
  event_id      int NOT NULL, 
  user_id       int NOT NULL, 
  registered_at timestamp DEFAULT current_timestamp() NOT NULL, 
  CONSTRAINT pk_event_partecipants
    PRIMARY KEY (id));
CREATE TABLE EventTypes (
  id   int NOT NULL, 
  name varchar(255) NOT NULL, 
  CONSTRAINT pk_event_types
    PRIMARY KEY (id));
CREATE TABLE TypicalPackages (
  id          int NOT NULL, 
  name        varchar(255) NOT NULL, 
  description varchar(255), 
  price       numeric(19, 0) NOT NULL, 
  producer_id int NOT NULL, 
  is_active   tinyint DEFAULT 1 NOT NULL, 
  CONSTRAINT pk_typical_packages
    PRIMARY KEY (id));
CREATE TABLE TypicalPackagesItems (
  id                 int NOT NULL, 
  typical_package_id int NOT NULL, 
  product_id         int NOT NULL, 
  quantity           int NOT NULL,
  CONSTRAINT pk_typical_packages_items
      PRIMARY KEY (id));
CREATE TABLE ProductsTransformations (
  id                int NOT NULL, 
  input_product_id  int NOT NULL, 
  output_product_id int NOT NULL, 
  step_id           int NOT NULL, 
  CONSTRAINT pk_products_transformations
    PRIMARY KEY (id));
CREATE TABLE CompanyTypes (
  id          int NOT NULL, 
  name        varchar(255) NOT NULL, 
  description varchar(255), 
  CONSTRAINT pk_company_types
    PRIMARY KEY (id));
CREATE TABLE CompaniesCompanyTypes (
  id              int NOT NULL, 
  company_id      int NOT NULL, 
  company_type_id int NOT NULL, 
  CONSTRAINT pk_companies_company_types
    PRIMARY KEY (id));
CREATE TABLE ProductsReviews (
  id         int NOT NULL, 
  product_id int NOT NULL, 
  user_id    int NOT NULL, 
  rating     int NOT NULL, 
  comment    varchar(255), 
  CONSTRAINT pk_products_reviews
    PRIMARY KEY (id));
CREATE TABLE Tables (
  id   int GENERATED BY DEFAULT AS IDENTITY, 
  name varchar(255) NOT NULL, 
  CONSTRAINT pk_tables
    PRIMARY KEY (id));
CREATE TABLE ProductsListing (
  id                 int NOT NULL, 
  product_id         int NOT NULL, 
  seller_id          int NOT NULL, 
  price              numeric(19, 0) NOT NULL, 
  quantity_available int DEFAULT 0 NOT NULL, 
  unit_of_measure    varchar(255), 
  is_active          tinyint DEFAULT 1 NOT NULL, 
  CONSTRAINT pk_products_listing
    PRIMARY KEY (id));
ALTER TABLE Products ADD CONSTRAINT FKProducts832433 FOREIGN KEY (category_id) REFERENCES PRODUCT_CATEGORIES (id);
ALTER TABLE PRODUCT_CATEGORIES ADD CONSTRAINT FKProductsCa333050 FOREIGN KEY (parent_id) REFERENCES PRODUCT_CATEGORIES (id);
ALTER TABLE Products ADD CONSTRAINT FKProducts967807 FOREIGN KEY (cultivation_method_id) REFERENCES CULTIVATION_METHODS (id);
ALTER TABLE Products ADD CONSTRAINT FKProducts333592 FOREIGN KEY (harvest_season_id) REFERENCES HARVEST_SEASONS (id);
ALTER TABLE Requests ADD CONSTRAINT FKRequests941478 FOREIGN KEY (target_table_id) REFERENCES DB_TABLES (id);
ALTER TABLE ChangeLogs ADD CONSTRAINT FKChangeLogs355938 FOREIGN KEY (table_id) REFERENCES DB_TABLES (id);
ALTER TABLE ChangeLogs ADD CONSTRAINT FKChangeLogs861214 FOREIGN KEY (changed_by) REFERENCES Users (id);
ALTER TABLE Requests ADD CONSTRAINT FKRequests161355 FOREIGN KEY (requester_id) REFERENCES Users (id);
ALTER TABLE Users ADD CONSTRAINT FKUsers711135 FOREIGN KEY (role_id) REFERENCES USER_ROLES (id);
ALTER TABLE PRODUCT_LISTINGS ADD CONSTRAINT FKProductsLi376923 FOREIGN KEY (product_id) REFERENCES Products (id);
ALTER TABLE PRODUCT_LISTINGS ADD CONSTRAINT FKProductsLi165062 FOREIGN KEY (seller_id) REFERENCES Companies (id);
ALTER TABLE Companies ADD CONSTRAINT FKCompanies657217 FOREIGN KEY (owner_id) REFERENCES Users (id);
ALTER TABLE Companies ADD CONSTRAINT FKCompanies238615 FOREIGN KEY (location_id) REFERENCES Locations (id);
ALTER TABLE TYPICAL_PACKAGES ADD CONSTRAINT FKTypicalPac633778 FOREIGN KEY (producer_id) REFERENCES Companies (id);
ALTER TABLE Requests ADD CONSTRAINT FKRequests52014 FOREIGN KEY (curator_id) REFERENCES Users (id);
ALTER TABLE Orders ADD CONSTRAINT FKOrders457904 FOREIGN KEY (buyer_id) REFERENCES Users (id);
ALTER TABLE Orders ADD CONSTRAINT FKOrders420253 FOREIGN KEY (seller_id) REFERENCES Companies (id);
ALTER TABLE Orders ADD CONSTRAINT FKOrders311009 FOREIGN KEY (delivery_location_id) REFERENCES Locations (id);
ALTER TABLE COMPANY_COMPANY_TYPES ADD CONSTRAINT FKCompaniesC839920 FOREIGN KEY (company_type_id) REFERENCES COMPANY_TYPES (id);
ALTER TABLE COMPANY_COMPANY_TYPES ADD CONSTRAINT FKCompaniesC134405 FOREIGN KEY (company_id) REFERENCES Companies (id);
ALTER TABLE Events ADD CONSTRAINT FKEvents27698 FOREIGN KEY (event_type_id) REFERENCES EVENT_TYPES (id);
ALTER TABLE Events ADD CONSTRAINT FKEvents361433 FOREIGN KEY (location_id) REFERENCES Locations (id);
ALTER TABLE EVENT_PARTECIPANTS ADD CONSTRAINT FKEventParte450221 FOREIGN KEY (event_id) REFERENCES Events (id);
ALTER TABLE EVENT_PARTECIPANTS ADD CONSTRAINT FKEventParte788152 FOREIGN KEY (user_id) REFERENCES Users (id);
ALTER TABLE USER_COMPANY ADD CONSTRAINT FKUsersCompa826836 FOREIGN KEY (user_id) REFERENCES Users (id);
ALTER TABLE USER_COMPANY ADD CONSTRAINT FKUsersCompa395446 FOREIGN KEY (company_id) REFERENCES Companies (id);
ALTER TABLE PRODUCTION_STEPS ADD CONSTRAINT FKProduction590696 FOREIGN KEY (product_id) REFERENCES Products (id);
ALTER TABLE PRODUCTION_STEPS ADD CONSTRAINT FKProduction159907 FOREIGN KEY (company_id) REFERENCES Companies (id);
ALTER TABLE PRODUCTION_STEPS ADD CONSTRAINT FKProduction797821 FOREIGN KEY (location_id) REFERENCES Locations (id);
ALTER TABLE ORDER_ITEMS ADD CONSTRAINT FKOrderItems960372 FOREIGN KEY (order_id) REFERENCES Orders (id);
ALTER TABLE ORDER_ITEMS ADD CONSTRAINT FKOrderItems729798 FOREIGN KEY (product_listing_id) REFERENCES PRODUCT_LISTINGS (id);
ALTER TABLE PRODUCT_CERTIFICATION ADD CONSTRAINT FKProductsCe935361 FOREIGN KEY (product_id) REFERENCES Products (id);
ALTER TABLE PRODUCT_CERTIFICATION ADD CONSTRAINT FKProductsCe881021 FOREIGN KEY (certification_id) REFERENCES Certifications (id);
ALTER TABLE COMPANY_CERTIFICATIONS ADD CONSTRAINT FKCompaniesC522106 FOREIGN KEY (company_id) REFERENCES Companies (id);
ALTER TABLE COMPANY_CERTIFICATIONS ADD CONSTRAINT FKCompaniesC863487 FOREIGN KEY (certification_id) REFERENCES Certifications (id);
ALTER TABLE PRODUCT_REVIEWS ADD CONSTRAINT FKProductsRe355336 FOREIGN KEY (product_id) REFERENCES Products (id);
ALTER TABLE PRODUCT_REVIEWS ADD CONSTRAINT FKProductsRe355937 FOREIGN KEY (user_id) REFERENCES Users (id);
ALTER TABLE PRODUCT_TRANSFORMATIONS ADD CONSTRAINT FKProductsTr951193 FOREIGN KEY (input_product_id) REFERENCES Products (id);
ALTER TABLE PRODUCT_TRANSFORMATIONS ADD CONSTRAINT FKProductsTr473355 FOREIGN KEY (output_product_id) REFERENCES Products (id);
ALTER TABLE TYPICAL_PACKAGES_ITEMS ADD CONSTRAINT FKTypicalPac412048 FOREIGN KEY (typical_package_id) REFERENCES TYPICAL_PACKAGES (id);
ALTER TABLE TYPICAL_PACKAGES_ITEMS ADD CONSTRAINT FKTypicalPac820231 FOREIGN KEY (product_id) REFERENCES Products (id);
